id: I06E99E9E
legacy_id: P005622
ocr_import_info:
  bdrc_scan_id: W8LS20227
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T23:20:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T13:20:36.279685+00:00'
last_modified: 2022-08-27 21:20:49.351012
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS20227
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS20227
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷ་སའི་སྐད་ཀྱི་རྨང་གཞི་སློབ་དེབ།
  author: ཉི་མ་སྒྲོལ་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9128830976136899
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I8LS20229:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS20229
      total_pages: 273
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS20229.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9128830976136899
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
