id: P005622
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20227
  title: ལྷ་སའི་སྐད་ཀྱི་རྨང་གཞི་སློབ་དེབ།
  author: ''
  volumes:
    232b238a7a714f81968c549459e01cc7:
      image_group_id: I8LS20229
      title: ''
      volume_number: 1
      total_pages: 273
      base_file: v001.txt
