id: P005622
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:07:48.650877
source_metadata:
  id: bdr:W8LS20227
  title: ལྷ་སའི་སྐད་ཀྱི་རྨང་གཞི་སློབ་དེབ།
  author: ''
  volumes:
    232b238a7a714f81968c549459e01cc7:
      image_group_id: I8LS20229
      title: ''
      volume_number: 1
      total_pages: 273
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
